### PR TITLE
Apply some static analysis suggestions. Cleanup code

### PR DESCRIPTION
**Pull request by Sciencentistguy**

### CODE REVIEW

**Review by MattYoung-UoY — CHANGES_REQUESTED** [review]
Proposed Changes:

1. (Colours.java:29) r, g, and b attributes in Colours Enum to be declared on the same line (they serve similar purposes, and so it is not unreasonable to declare them together).
2. (Colours.java:31) Keep the private enum constructor. Private Enum Constructor included for Defensive programming purposes. Having the Enum Constructor be package protected serves no purpose, and it is not intended for the Enum constructor to be invoked outside of Colours.
3. (Main.java:146) Assertion not needed. If Colours is empty, then there's no point running the program, as there are no lego bricks to form the result from. (An issue will be made to make sure that Colours is checked to make sure that it is not empty once custom Brick Lists are implemented).
4. (Main.java:160) Remove this change. This bad loop style occurs elsewhere as well, but there is a better way to do it. (An issue will be made and this will be fixed in a future commit.)

**Comment by Sciencentistguy** [comment]
I actually (somewhat unsurprisingly) have some opinions on these comments:
1. Having three lines makes it less ambiguous that all three variables are final, not just the first one.
2. Defensive programming only makes sense in the context of library design. Not giving the constructor a visibility keyword makes the code more readable.
3. I would suggest to keep the assertion, to be removed when that issue is closed.
4. All bad loops is worse than All bad loops - 1 bad loop

**Comment by MattYoung-UoY** [comment]
1. I'd rather they remain on the one line, for style reasons. The application of final to all three attributes should be fairly easy to understand.
2. True, but I'd rather keep it in the case that someone else decides to make a fork and accidentally does something unintended. If they want to change the behaviour to add to Colours, that should mean that they know what they're doing in regards to removing the Private modifier.

I will give you 3 & 4. Those are fair points.

**Comment by Sciencentistguy** [comment]
Having consulted both stackoverflow (https://stackoverflow.com/questions/7113363/private-enum-constructor) and IntelliJ
image

It appears that all enum constructors are private. So the word private there is entirely redundant.

I've changed the first one.

**Comment by MattYoung-UoY** [comment]
Change the for loop var name at Main:160 from pixel to something more intuitive/appropriate like col, and I'll merge the changes 😁

**Review by MattYoung-UoY — APPROVED** [review]
Looks good to me =D

**Pull request merged**
